version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: justin1369/graph-service:1.1
    ports:
      - "8081:8080"
    volumes:
      - ./config.json:/app/config.json
