// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Bill struct {
	ID   string `json:"id"`
	Type string `json:"type"`
	Code string `json:"code"`
}

type Mutation struct {
}

type NewOrder struct {
	ID     string `json:"id"`
	UserID string `json:"userId"`
	Name   string `json:"name"`
	Type   string `json:"type"`
	BillID string `json:"billId"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Order struct {
	ID     string `json:"id"`
	UserID string `json:"userId"`
	Name   string `json:"name"`
	Type   string `json:"type"`
	Bill   *Bill  `json:"bill"`
}

type Query struct {
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
